version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/html
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - db

  db:
    image: mysql:5.7.22
    command: --character-set-server=utf8mb4
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: shop_online
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - db